- include_vars: "{{ item }}"
  with_first_found:
    - "RedHat.yml"
  tags: httpd

- name: Ensure Apache is installed
  package:
    name: "{{ item }}"
    state: present
  with_items: "{{ httpd_packages }}"
  tags: httpd

- name: Realod deamon
  shell: |
    systemctl daemon-reload

- name: Install main configuration file
  template:
    src: httpd.conf.j2
    dest: "{{ httpd_config }}"
    owner: root
    group: root
    setype: httpd_config_t
    mode: '0644'
  notify: restart httpd
  tags: httpd

# I assume that we have some artifacts repository 
- name: Download HTML file
  get_url:
    # url: "http://artifactory/project/{{ html_file_version }}/index.html"
    url: https://github.com/htmlpreview/htmlpreview.github.com/blob/master/index.html
    dest: /var/www/html/index.html
    owner: root
    group: root
    mode: '0644'
    force: yes 
  notify: restart httpd
  tags: 
    - httpd
    - deploy

- name: Download CSS file
  get_url:
    # url: "http://artifactory/project/{{ html_file_version }}/file.css"
    url: https://github.com/htmlpreview/htmlpreview.github.com/blob/master/index.html
    dest: /var/www/html/file.css
    owner: root
    group: root
    mode: '0644'
    force: yes
  notify: restart httpd
  tags: 
    - httpd
    - deploy

- name: Install status configuration file
  template:
    src: etc_httpd_conf.d_status.conf.j2
    dest: "{{ httpd_status_config }}"
    owner: root
    group: root
    setype: httpd_config_t
    mode: '0644'
  notify: restart httpd
  tags: httpd
  when: httpd_status_enable

- name: Install certificate files
  include_tasks: certificates.yml
  tags: httpd

- name: Install mod_ssl configuration file
  template:
    src: ssl.conf.j2
    dest: "{{ httpd_ssl_config }}"
    owner: root
    group: root
    setype: httpd_config_t
    mode: '0644'
  notify: restart httpd
  tags: httpd
